### ISSUE TITLE
Automatic configuration update system

### ISSUE THREAD

**Issue by beaconcreaft** [UnknowG/PlayerAnnouncement#2]
when I type the command /pb and not written just command it, and I press send end boom erorr internal. and it shouldn't be so in the messages.yml ("empty-message-error)

![Screenshot_20190704-225855](https://user-images.githubusercontent.com/34483380/60678634-5a1fa700-9eaf-11e9-82a1-e79b97e4915a.png)

should add {name} if you want /pb, so that publicly know, who typed the command /pb.
like a command /says he uses {name}.

**Comment by beaconcreaft** [comment]
like a command /says

**Comment by Bluzzi** [comment]
Hello, deleted the config and try again, I will make a system to automatically update the config.

For the {name} it's true that it's an omission that's important though: p I'll add it too ;)

**Comment by beaconcreaft** [comment]
> Halo, hapus konfigurasi dan coba lagi, saya akan membuat sistem untuk memperbarui konfigurasi secara otomatis.
> 
> Untuk {nama} memang benar bahwa itu adalah penghilangan yang penting: p saya akan menambahkannya juga;)

Nice, thx i like this plugins xD. I'm waiting for the update :3

**Comment by UnknowG** [comment]
@beaconcreaft Thank you for this error report.
Feel free to share your mistakes

**Comment by Bluzzi** [comment]
This issue is not closed: https://github.com/UnknowG/PlayerAnnouncement/issues/2#issuecomment-508529770 !

**Comment by Bluzzi** [comment]
This is another problem.

**Comment by beaconcreaft** [comment]
but I have changed EconommyAPI with the latest version.
and I'm confused MISTAKE because of where?

**Comment by beaconcreaft** [comment]
> This is another problem.

but I have changed EconommyAPI with the latest version.
and I am confused MISTAKE because of where?

**Comment by beaconcreaft** [comment]
> This is another problem.

but I have changed EconommyAPI with the latest version.
and I am confused MISTAKE because of where?
