### ISSUE TITLE
can't display {name}

### ISSUE THREAD

**Issue by beaconcreaft** [UnknowG/PlayerAnnouncement#3]
has {name} been added in this plugin? to be able to display nametag

**Comment by beaconcreaft** [comment]
plugins that I wait for, and the important ones are updates can display nametag

**Comment by UnknowG** [comment]
No the name is not avaible for this moment on the next update it will be available

**Comment by beaconcreaft** [comment]
> Tidak ada nama yang tidak tersedia untuk saat ini pada pembaruan berikutnya akan tersedia

Thx, because I need this plugin:3

**Comment by UnknowG** [comment]
I'm currently working on it but I have something that's getting stuck and I'm trying to do it as soon as possible:)

**Comment by beaconcreaft** [comment]
> Saat ini saya sedang mengusahakannya tetapi saya memiliki sesuatu yang macet dan saya mencoba untuk melakukannya sesegera mungkin :)

> I'm currently working on it but I have something that's getting stuck and I'm trying to do it as soon as possible:)

Okyy:')

**Comment by UnknowG** [comment]
I finished the version I test it and I publish it on GitHub :)

**Comment by UnknowG** [comment]
Option added !

**Comment by beaconcreaft** [comment]
> I finished the version I test it and I publish it on GitHub :)

Hmm sorry, maybe this isn't interesting

why isn't {name} used in config.yml?
Example: 
I use a command /pb Hello all
and displaying : (broadcast-VIP) from {name} : Hello all
can it be like that?

**Comment by beaconcreaft** [comment]
> > I finished the version I test it and I publish it on GitHub :)
> 
> Hmm sorry, maybe this isn't interesting
> 
> why isn't {name} used in config.yml?
> Example:
> I use a command /pb Hello all
> and displaying : (broadcast-VIP) from {name} : Hello all
> can it be like that?

And his name can be seen by the public

**Comment by UnknowG** [comment]
You can change the position of {name} in the configuration

I'm not sure I understand your request very well.

**Comment by beaconcreaft** [comment]
I guess that won't work:3
and sorry if i can't speak english.
Iam from indonesian country

**Comment by beaconcreaft** [comment]
> You can change the position of {name} in the configuration (message.yml)
> 
> I'm not sure I understand your request very well.

I guess that won't work:3
and sorry if i can't speak english.
Iam from indonesian country

**Comment by UnknowG** [comment]
see I'm going to have to stop because I'm a little tired of developing right now I'm going to have some fun so at worst if @Bluzzi or @Virvolta goes through it will help you or add your proposal

If no one helps you or sees it I'll come back around 6pm (French Time) and for you I think it'll be at 11pm if I'm not mistaken (18h FR) (23h You)

**Comment by beaconcreaft** [comment]
> see I'm going to have to stop because I'm a little tired of developing right now I'm going to have some fun so at worst if @Bluzzi or @Virvolta goes through it will help you or add your proposal
> 
> If no one helps you or sees it I'll come back around 6pm (French Time) and for you I think it'll be at 11pm if I'm not mistaken (18h FR) (23h You)

Sorry, maybe next time bruh

**Comment by Bluzzi** [comment]
Hello @beaconcreaft, I added the possibility to display the player's name in the prefix, do you like this or are you thinking of another solution ?

Phar: https://www.dropbox.com/s/hckc6kcd272irym/PlayerAnnouncement.phar?dl=0

**Comment by Bluzzi** [comment]
#5 (he answered here 🤦‍♂)
