### ISSUE TITLE
Not working on the console

### ISSUE THREAD

**Issue by beaconcreaft** [UnknowG/PlayerAnnouncement#5]
does not work. ERROR
/pb
/pbreload

**Comment by Bluzzi** [comment]
Error ??

**Comment by beaconcreaft** [comment]
> Error ??

Yeah not work... and has it been tested? with you alone

**Comment by beaconcreaft** [comment]
I tried it and the results did not appear

**Comment by Bluzzi** [comment]
You must have made a error in your console ! Do you have the latest version of the plugin ?

Phar 1.8: https://www.dropbox.com/s/hckc6kcd272irym/PlayerAnnouncement.phar?dl=0

**Comment by beaconcreaft** [comment]
> I tried it and the results did not appear

Hmm, sorry my ecconommy error not detected:v

**Comment by beaconcreaft** [comment]
> You must have made a error in your console ! Do you have the latest version of the plugin ?
> 
> Phar 1.8: https://www.dropbox.com/s/hckc6kcd272irym/PlayerAnnouncement.phar?dl=0

Plug Dev #44 or dropbox, not work:3 why? 
I type / pb is still not working
I type / pbreload is still not working

**Comment by beaconcreaft** [comment]
> You must have made a error in your console ! Do you have the latest version of the plugin ?
> 
> Phar 1.8: https://www.dropbox.com/s/hckc6kcd272irym/PlayerAnnouncement.phar?dl=0

Nice, workk sorry bruh.. plug Dev #44 work in game, and not work in console, btw plugin nice and You have realized what I want
